fix: pin transformers to v4.49.0 to fix ImportError: cannot import name 'AdamW' from 'transformers'
In the latest version of [transformers v4.51.3](https://github.com/huggingface/transformers/blob/v4.51.3/src/transformers/__init__.py), they removed the `AdamW` optimizer which causes `ImportError: cannot import name 'AdamW' from 'transformers' `. Pinning to the latest version of transformers which does have the AdamW optimizer fixes this issue.