Update geneformer/in_silico_perturber.py
Thank you very much for your great work.

But I found two errors when I tried to use this model to perturb one gene on my datasets (which means I input a list with the esemble id of the gene I want to perturb).

The first one I found is that the dimensions of minibatch_emb and minibatch_comparison are usually not the same and the difference is equal to 1 all the time. This happened when batches were padded.(needs_pad_or_trunc == True in Function compute_batch_embeddings).

This is because original batch samples were padded with the max length of perturbed batch samples, which is one token (perturb_gene) less than the true max length. In this step, the lenghts of original and perturbed samples are the same (but not a correct process). After the embeddings were calculated, the embedding of perturb gene in original data is removed by function remove_indices_from_emb_batch. This is step cause the difference between the length of original and perturbed batch samples (however this step is a correct process).

So what we need to do is padding the original samples with their own max length, which can be quite easy. Just keep the parameter  _max_len==None.

The second error happened successively. It's also because of the vairous token lengths of different batches. One can either pad them to the same length(eg. 2048) or use a list to store them. I choose the latter one.

Additional, when I provide more than one gene in the list with the model, a different error will also occur. Sorry, I have not find time to dive into that issue.

But at least, this script can handle with one gene deletion perturbation :D .

----------------------------------------------------------------------------------------

Supplymentary:
My Params:
isp = InSilicoPerturber(perturb_type="delete",
                        perturb_rank_shift=None,
                        genes_to_perturb=["ENSGxxxxxx"], 
                        combos=0,
                        anchor_gene=None,
                        model_type="Pretrained",
                        num_classes=0,
                        emb_mode="cell_and_gene",
                        cell_emb_style="mean_pool",
                        cell_states_to_model=None,
                        max_ncells=None, 
                        emb_layer=-1, 
                        forward_batch_size=16,
                        nproc=16)
isp.perturb_data("../fine_tuned_models/with_my_data/models",
                 "../datasets/my_data.dataset",
                 "../outputs/perturb_GENE/",
                 "perturb_GENE")

ERROR1:
RuntimeError: The size of tensor a (2047) must match the size of tensor b (2046) at non-singleton dimension 1

Evidence for ERROR1:
[PADDING]
minibatch_length_set{2019, 2021, 2023, 2024, 2025, 2026, 2027, 2030}
input_data_minibatch.shape:torch.Size([16, 2030])
minibatch_length_set{2020, 2022, 2024, 2025, 2026, 2027, 2028, 2031}
input_data_minibatch.shape:torch.Size([16, 2030])
[QUANT_COS_SIM]
minibatch_emb.shape:torch.Size([16, 2030, 256]),
minibatch_comparison.shape:torch.Size([16, 2029, 256])

ERROR2:
Traceback (most recent call last):
  File "in_silico_perturbation.py", line 31, in <module>
    isp.perturb_data("../fine_tuned_models/with_my_data/models",
  File "/Geneformer/geneformer/in_silico_perturber.py", line 1045, in perturb_data
    self.in_silico_perturb(model,
  File "/Geneformer/geneformer/in_silico_perturber.py", line 1133, in in_silico_perturb
    cos_sims_data = quant_cos_sims(model, 
  File "/Geneformer/geneformer/in_silico_perturber.py", line 534, in quant_cos_sims
    cos_sims_stack = torch.cat(cos_sims)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 2047 but got size 2046 for tensor number 24 in the list.

ADDITIONAL ERROR:
[PARAM]
genes_to_perturb=["ENSGxxxxxx1","ENSGxxxxxx2"] 
[ERROR]
Traceback (most recent call last):
  File "in_silico_perturbation.py", line 31, in <module>
    isp.perturb_data("../fine_tuned_models/with_my_data/models",
  File "/Geneformer/geneformer/in_silico_perturber.py", line 984, in perturb_data
    filtered_input_data,
  File "/Geneformer/geneformer/in_silico_perturber.py", line 1062, in in_silico_perturb
    self.perturb_type,
  File "/Geneformer/geneformer/in_silico_perturber.py", line 426, in quant_cos_sims
    end_range = [i for i in range(orig_max_len - tokens_to_perturb, orig_max_len)]
TypeError: unsupported operand type(s) for -: 'int' and 'list'